name: github_mini
description: "A GitHub profile viewer app with repositories list and details"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # State Management
  get: ^4.7.2  # GetX for state management and navigation

  # Network
  dio: ^5.3.3  # HTTP client for API requests
  connectivity_plus: ^5.0.1  # Check network connectivity
  
  # UI Components
  shimmer: ^3.0.0  # Loading animations
  cached_network_image: ^3.3.0  # Cache images
  url_launcher: ^6.2.2  # Launch URLs
  flutter_markdown: ^0.6.18  # Markdown rendering
  
  # Storage
  hive: ^2.2.3  # NoSQL database
  hive_flutter: ^1.1.0  # Hive extension for Flutter
  flutter_secure_storage: ^9.0.0  # Secure storage for tokens
  
  # Models
  freezed_annotation: ^2.4.1  # Immutable models
  json_annotation: ^4.8.1  # JSON serialization
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code Generation
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  
  # App Icon
  flutter_launcher_icons: ^0.13.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
